apiVersion: v1
kind: PersistentVolume
metadata:
  name: zazzle-agent-pv
  namespace: zazzle-agent
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/zazzle-agent"
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zazzle-agent-pvc
  namespace: zazzle-agent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi 