apiVersion: apps/v1
kind: Deployment
metadata:
  name: zazzle-agent-pipeline
  namespace: zazzle-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zazzle-agent-pipeline
  template:
    metadata:
      labels:
        app: zazzle-agent-pipeline
    spec:
      containers:
      - name: pipeline
        image: ghcr.io/sctennis77/zazzle-agent/pipeline:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: zazzle-agent-config
              key: DATABASE_URL
        - name: PIPELINE_SCHEDULE
          valueFrom:
            configMapKeyRef:
              name: zazzle-agent-config
              key: PIPELINE_SCHEDULE
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: zazzle-agent-secrets
              key: OPENAI_API_KEY
        - name: REDDIT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: zazzle-agent-secrets
              key: REDDIT_CLIENT_ID
        - name: REDDIT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: zazzle-agent-secrets
              key: REDDIT_CLIENT_SECRET
        - name: REDDIT_USER_AGENT
          valueFrom:
            secretKeyRef:
              name: zazzle-agent-secrets
              key: REDDIT_USER_AGENT
        - name: ZAZZLE_AFFILIATE_ID
          valueFrom:
            secretKeyRef:
              name: zazzle-agent-secrets
              key: ZAZZLE_AFFILIATE_ID
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: zazzle-agent-pvc 