apiVersion: v1
kind: Secret
metadata:
  name: zazzle-agent-secrets
  namespace: zazzle-agent
type: Opaque
data:
  # These will be base64 encoded in the actual deployment
  # In GitHub Actions, these come from repository secrets
  openai-api-key: ${OPENAI_API_KEY_BASE64}
  reddit-client-id: ${REDDIT_CLIENT_ID_BASE64}
  reddit-client-secret: ${REDDIT_CLIENT_SECRET_BASE64}
  reddit-user-agent: ${REDDIT_USER_AGENT_BASE64}
  zazzle-affiliate-id: ${ZAZZLE_AFFILIATE_ID_BASE64}
  imgur-client-id: ${IMGUR_CLIENT_ID_BASE64}
  imgur-client-secret: ${IMGUR_CLIENT_SECRET_BASE64} 