apiVersion: v1
kind: Secret
metadata:
  name: zazzle-agent-secrets
  namespace: zazzle-agent
type: Opaque
data:
  # These values should be base64 encoded
  # Example: echo -n "your-api-key" | base64
  OPENAI_API_KEY: ""  # Add your base64 encoded OpenAI API key
  REDDIT_CLIENT_ID: ""  # Add your base64 encoded Reddit client ID
  REDDIT_CLIENT_SECRET: ""  # Add your base64 encoded Reddit client secret
  REDDIT_USER_AGENT: ""  # Add your base64 encoded Reddit user agent
  ZAZZLE_AFFILIATE_ID: ""  # Add your base64 encoded Zazzle affiliate ID 