"""add comment_summary to RedditPost and remove CommentSummary table

Revision ID: 0ba9ef219ecf
Revises: 
Create Date: 2025-06-16 09:16:49.607962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ba9ef219ecf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_summaries')
    op.add_column('reddit_posts', sa.Column('comment_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_posts', 'comment_summary')
    op.create_table('comment_summaries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reddit_post_id', sa.INTEGER(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['reddit_post_id'], ['reddit_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
