"""add comment_summary to RedditPost and remove CommentSummary table

Revision ID: 10239f8de469
Revises: e094d5e5c9ed
Create Date: 2025-06-26 19:56:23.385328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10239f8de469'
down_revision: Union[str, None] = 'e094d5e5c9ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
