"""add ProductRedditComment table for comment tracking

Revision ID: 199317be58cb
Revises: 0c44bf314eb7
Create Date: 2025-07-18 15:19:56.366065

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "199317be58cb"
down_revision: Union[str, Sequence[str], None] = "254c0379b616"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create ProductRedditComment table
    op.create_table(
        "product_reddit_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_info_id", sa.Integer(), nullable=False),
        sa.Column("original_post_id", sa.String(length=32), nullable=False),
        sa.Column("comment_id", sa.String(length=32), nullable=True),
        sa.Column("comment_url", sa.Text(), nullable=True),
        sa.Column("subreddit_name", sa.String(length=100), nullable=True),
        sa.Column("commented_at", sa.DateTime(), nullable=False),
        sa.Column("comment_content", sa.Text(), nullable=True),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("engagement_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_info_id"],
            ["product_infos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_reddit_comments_comment_id"),
        "product_reddit_comments",
        ["comment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_reddit_comments_commented_at"),
        "product_reddit_comments",
        ["commented_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_reddit_comments_original_post_id"),
        "product_reddit_comments",
        ["original_post_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_reddit_comments_product_info_id"),
        "product_reddit_comments",
        ["product_info_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_reddit_comments_subreddit_name"),
        "product_reddit_comments",
        ["subreddit_name"],
        unique=False,
    )

    # Skip the problematic constraint changes for now
    # op.drop_constraint(op.f('uq_agent_scanned_posts_post_id'), 'agent_scanned_posts', type_='unique')
    # op.drop_index(op.f('ix_agent_scanned_posts_post_id'), table_name='agent_scanned_posts')
    # op.create_index(op.f('ix_agent_scanned_posts_post_id'), 'agent_scanned_posts', ['post_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop ProductRedditComment table
    op.drop_index(
        op.f("ix_product_reddit_comments_subreddit_name"),
        table_name="product_reddit_comments",
    )
    op.drop_index(
        op.f("ix_product_reddit_comments_product_info_id"),
        table_name="product_reddit_comments",
    )
    op.drop_index(
        op.f("ix_product_reddit_comments_original_post_id"),
        table_name="product_reddit_comments",
    )
    op.drop_index(
        op.f("ix_product_reddit_comments_commented_at"),
        table_name="product_reddit_comments",
    )
    op.drop_index(
        op.f("ix_product_reddit_comments_comment_id"),
        table_name="product_reddit_comments",
    )
    op.drop_table("product_reddit_comments")

    # Skip the problematic constraint changes for now
    # op.drop_index(op.f('ix_agent_scanned_posts_post_id'), table_name='agent_scanned_posts')
    # op.create_index(op.f('ix_agent_scanned_posts_post_id'), 'agent_scanned_posts', ['post_id'], unique=False)
    # op.create_unique_constraint(op.f('uq_agent_scanned_posts_post_id'), 'agent_scanned_posts', ['post_id'])
    # ### end Alembic commands ###
