"""add_reddit_username_to_donations

Revision ID: 296335745ad1
Revises: b5de384eb7e0
Create Date: 2025-06-26 09:20:14.901288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296335745ad1'
down_revision: Union[str, None] = 'b5de384eb7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('reddit_username', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_donations_reddit_username'), 'donations', ['reddit_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_reddit_username'), table_name='donations')
    op.drop_column('donations', 'reddit_username')
    # ### end Alembic commands ###
