"""add_image_url_to_product_info

Revision ID: 2c1bf2279e63
Revises: 10239f8de469
Create Date: 2025-06-26 20:44:42.553892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1bf2279e63'
down_revision: Union[str, None] = '10239f8de469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_infos', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_infos', 'image_url')
    # ### end Alembic commands ###
