"""initial schema with subreddit normalization

Revision ID: 32a1a538ffb1
Revises: 
Create Date: 2025-06-26 16:38:47.995598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a1a538ffb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_end_time'), 'pipeline_runs', ['end_time'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_start_time'), 'pipeline_runs', ['start_time'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_table('sponsor_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsor_tiers_created_at'), 'sponsor_tiers', ['created_at'], unique=False)
    op.create_index(op.f('ix_sponsor_tiers_min_amount'), 'sponsor_tiers', ['min_amount'], unique=False)
    op.create_index(op.f('ix_sponsor_tiers_name'), 'sponsor_tiers', ['name'], unique=True)
    op.create_table('subreddits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subreddit_name', sa.String(length=100), nullable=False),
    sa.Column('reddit_id', sa.String(length=32), nullable=True),
    sa.Column('reddit_fullname', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('public_description', sa.Text(), nullable=True),
    sa.Column('created_utc', sa.DateTime(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.Column('over18', sa.Boolean(), nullable=False),
    sa.Column('spoilers_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subreddits_created_at'), 'subreddits', ['created_at'], unique=False)
    op.create_index(op.f('ix_subreddits_created_utc'), 'subreddits', ['created_utc'], unique=False)
    op.create_index(op.f('ix_subreddits_reddit_fullname'), 'subreddits', ['reddit_fullname'], unique=False)
    op.create_index(op.f('ix_subreddits_reddit_id'), 'subreddits', ['reddit_id'], unique=False)
    op.create_index(op.f('ix_subreddits_subreddit_name'), 'subreddits', ['subreddit_name'], unique=True)
    op.create_index(op.f('ix_subreddits_subscribers'), 'subreddits', ['subscribers'], unique=False)
    op.create_index(op.f('ix_subreddits_updated_at'), 'subreddits', ['updated_at'], unique=False)
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('component', sa.String(length=64), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_component'), 'error_logs', ['component'], unique=False)
    op.create_index(op.f('ix_error_logs_error_type'), 'error_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_error_logs_pipeline_run_id'), 'error_logs', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_error_logs_severity'), 'error_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_error_logs_timestamp'), 'error_logs', ['timestamp'], unique=False)
    op.create_table('pipeline_run_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('idea_model', sa.String(length=64), nullable=False),
    sa.Column('image_model', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('image_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_run_usages_created_at'), 'pipeline_run_usages', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_run_usages_pipeline_run_id'), 'pipeline_run_usages', ['pipeline_run_id'], unique=True)
    op.create_table('reddit_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('subreddit_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('comment_summary', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_posts_author'), 'reddit_posts', ['author'], unique=False)
    op.create_index(op.f('ix_reddit_posts_num_comments'), 'reddit_posts', ['num_comments'], unique=False)
    op.create_index(op.f('ix_reddit_posts_pipeline_run_id'), 'reddit_posts', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_reddit_posts_post_id'), 'reddit_posts', ['post_id'], unique=True)
    op.create_index(op.f('ix_reddit_posts_score'), 'reddit_posts', ['score'], unique=False)
    op.create_index(op.f('ix_reddit_posts_subreddit_id'), 'reddit_posts', ['subreddit_id'], unique=False)
    op.create_table('subreddit_fundraising_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subreddit_id', sa.Integer(), nullable=False),
    sa.Column('goal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subreddit_fundraising_goals_completed_at'), 'subreddit_fundraising_goals', ['completed_at'], unique=False)
    op.create_index(op.f('ix_subreddit_fundraising_goals_created_at'), 'subreddit_fundraising_goals', ['created_at'], unique=False)
    op.create_index(op.f('ix_subreddit_fundraising_goals_current_amount'), 'subreddit_fundraising_goals', ['current_amount'], unique=False)
    op.create_index(op.f('ix_subreddit_fundraising_goals_deadline'), 'subreddit_fundraising_goals', ['deadline'], unique=False)
    op.create_index(op.f('ix_subreddit_fundraising_goals_goal_amount'), 'subreddit_fundraising_goals', ['goal_amount'], unique=False)
    op.create_index(op.f('ix_subreddit_fundraising_goals_status'), 'subreddit_fundraising_goals', ['status'], unique=False)
    op.create_index(op.f('ix_subreddit_fundraising_goals_subreddit_id'), 'subreddit_fundraising_goals', ['subreddit_id'], unique=False)
    op.create_table('subreddit_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subreddit_id', sa.Integer(), nullable=False),
    sa.Column('tier_level', sa.Integer(), nullable=False),
    sa.Column('min_total_donation', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subreddit_tiers_completed_at'), 'subreddit_tiers', ['completed_at'], unique=False)
    op.create_index(op.f('ix_subreddit_tiers_created_at'), 'subreddit_tiers', ['created_at'], unique=False)
    op.create_index(op.f('ix_subreddit_tiers_min_total_donation'), 'subreddit_tiers', ['min_total_donation'], unique=False)
    op.create_index(op.f('ix_subreddit_tiers_status'), 'subreddit_tiers', ['status'], unique=False)
    op.create_index(op.f('ix_subreddit_tiers_subreddit_id'), 'subreddit_tiers', ['subreddit_id'], unique=False)
    op.create_index(op.f('ix_subreddit_tiers_tier_level'), 'subreddit_tiers', ['tier_level'], unique=False)
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('subreddit_id', sa.Integer(), nullable=True),
    sa.Column('reddit_username', sa.String(length=100), nullable=True),
    sa.Column('stripe_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('subreddit_fundraising_goal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subreddit_fundraising_goal_id'], ['subreddit_fundraising_goals.id'], ),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_created_at'), 'donations', ['created_at'], unique=False)
    op.create_index(op.f('ix_donations_customer_email'), 'donations', ['customer_email'], unique=False)
    op.create_index(op.f('ix_donations_reddit_username'), 'donations', ['reddit_username'], unique=False)
    op.create_index(op.f('ix_donations_status'), 'donations', ['status'], unique=False)
    op.create_index(op.f('ix_donations_stripe_payment_intent_id'), 'donations', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_donations_subreddit_fundraising_goal_id'), 'donations', ['subreddit_fundraising_goal_id'], unique=False)
    op.create_index(op.f('ix_donations_subreddit_id'), 'donations', ['subreddit_id'], unique=False)
    op.create_index(op.f('ix_donations_updated_at'), 'donations', ['updated_at'], unique=False)
    op.create_table('product_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('reddit_post_id', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=256), nullable=True),
    sa.Column('image_title', sa.String(length=256), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('affiliate_link', sa.Text(), nullable=True),
    sa.Column('template_id', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('product_type', sa.String(length=64), nullable=True),
    sa.Column('design_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reddit_post_id'], ['reddit_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_infos_image_title'), 'product_infos', ['image_title'], unique=False)
    op.create_index(op.f('ix_product_infos_model'), 'product_infos', ['model'], unique=False)
    op.create_index(op.f('ix_product_infos_pipeline_run_id'), 'product_infos', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_product_infos_product_type'), 'product_infos', ['product_type'], unique=False)
    op.create_index(op.f('ix_product_infos_reddit_post_id'), 'product_infos', ['reddit_post_id'], unique=False)
    op.create_index(op.f('ix_product_infos_template_id'), 'product_infos', ['template_id'], unique=False)
    op.create_index(op.f('ix_product_infos_theme'), 'product_infos', ['theme'], unique=False)
    op.create_table('interaction_agent_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_info_id', sa.Integer(), nullable=False),
    sa.Column('reddit_post_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('subreddit_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('success', sa.String(length=8), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['product_info_id'], ['product_infos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reddit_post_id'], ['reddit_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_agent_actions_action_type'), 'interaction_agent_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_interaction_agent_actions_product_info_id'), 'interaction_agent_actions', ['product_info_id'], unique=False)
    op.create_index(op.f('ix_interaction_agent_actions_reddit_post_id'), 'interaction_agent_actions', ['reddit_post_id'], unique=False)
    op.create_index(op.f('ix_interaction_agent_actions_subreddit_id'), 'interaction_agent_actions', ['subreddit_id'], unique=False)
    op.create_index(op.f('ix_interaction_agent_actions_success'), 'interaction_agent_actions', ['success'], unique=False)
    op.create_index(op.f('ix_interaction_agent_actions_target_id'), 'interaction_agent_actions', ['target_id'], unique=False)
    op.create_index(op.f('ix_interaction_agent_actions_target_type'), 'interaction_agent_actions', ['target_type'], unique=False)
    op.create_index(op.f('ix_interaction_agent_actions_timestamp'), 'interaction_agent_actions', ['timestamp'], unique=False)
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('subreddit_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['sponsor_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsors_created_at'), 'sponsors', ['created_at'], unique=False)
    op.create_index(op.f('ix_sponsors_donation_id'), 'sponsors', ['donation_id'], unique=False)
    op.create_index(op.f('ix_sponsors_status'), 'sponsors', ['status'], unique=False)
    op.create_index(op.f('ix_sponsors_subreddit_id'), 'sponsors', ['subreddit_id'], unique=False)
    op.create_index(op.f('ix_sponsors_tier_id'), 'sponsors', ['tier_id'], unique=False)
    op.create_table('pipeline_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('subreddit_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_tasks_completed_at'), 'pipeline_tasks', ['completed_at'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_created_at'), 'pipeline_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_pipeline_run_id'), 'pipeline_tasks', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_priority'), 'pipeline_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_scheduled_for'), 'pipeline_tasks', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_sponsor_id'), 'pipeline_tasks', ['sponsor_id'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_status'), 'pipeline_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_subreddit_id'), 'pipeline_tasks', ['subreddit_id'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_type'), 'pipeline_tasks', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_tasks_type'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_subreddit_id'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_status'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_sponsor_id'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_scheduled_for'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_priority'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_pipeline_run_id'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_created_at'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_completed_at'), table_name='pipeline_tasks')
    op.drop_table('pipeline_tasks')
    op.drop_index(op.f('ix_sponsors_tier_id'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_subreddit_id'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_status'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_donation_id'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_created_at'), table_name='sponsors')
    op.drop_table('sponsors')
    op.drop_index(op.f('ix_interaction_agent_actions_timestamp'), table_name='interaction_agent_actions')
    op.drop_index(op.f('ix_interaction_agent_actions_target_type'), table_name='interaction_agent_actions')
    op.drop_index(op.f('ix_interaction_agent_actions_target_id'), table_name='interaction_agent_actions')
    op.drop_index(op.f('ix_interaction_agent_actions_success'), table_name='interaction_agent_actions')
    op.drop_index(op.f('ix_interaction_agent_actions_subreddit_id'), table_name='interaction_agent_actions')
    op.drop_index(op.f('ix_interaction_agent_actions_reddit_post_id'), table_name='interaction_agent_actions')
    op.drop_index(op.f('ix_interaction_agent_actions_product_info_id'), table_name='interaction_agent_actions')
    op.drop_index(op.f('ix_interaction_agent_actions_action_type'), table_name='interaction_agent_actions')
    op.drop_table('interaction_agent_actions')
    op.drop_index(op.f('ix_product_infos_theme'), table_name='product_infos')
    op.drop_index(op.f('ix_product_infos_template_id'), table_name='product_infos')
    op.drop_index(op.f('ix_product_infos_reddit_post_id'), table_name='product_infos')
    op.drop_index(op.f('ix_product_infos_product_type'), table_name='product_infos')
    op.drop_index(op.f('ix_product_infos_pipeline_run_id'), table_name='product_infos')
    op.drop_index(op.f('ix_product_infos_model'), table_name='product_infos')
    op.drop_index(op.f('ix_product_infos_image_title'), table_name='product_infos')
    op.drop_table('product_infos')
    op.drop_index(op.f('ix_donations_updated_at'), table_name='donations')
    op.drop_index(op.f('ix_donations_subreddit_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_subreddit_fundraising_goal_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_stripe_payment_intent_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_status'), table_name='donations')
    op.drop_index(op.f('ix_donations_reddit_username'), table_name='donations')
    op.drop_index(op.f('ix_donations_customer_email'), table_name='donations')
    op.drop_index(op.f('ix_donations_created_at'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_subreddit_tiers_tier_level'), table_name='subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_subreddit_id'), table_name='subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_status'), table_name='subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_min_total_donation'), table_name='subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_created_at'), table_name='subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_completed_at'), table_name='subreddit_tiers')
    op.drop_table('subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_fundraising_goals_subreddit_id'), table_name='subreddit_fundraising_goals')
    op.drop_index(op.f('ix_subreddit_fundraising_goals_status'), table_name='subreddit_fundraising_goals')
    op.drop_index(op.f('ix_subreddit_fundraising_goals_goal_amount'), table_name='subreddit_fundraising_goals')
    op.drop_index(op.f('ix_subreddit_fundraising_goals_deadline'), table_name='subreddit_fundraising_goals')
    op.drop_index(op.f('ix_subreddit_fundraising_goals_current_amount'), table_name='subreddit_fundraising_goals')
    op.drop_index(op.f('ix_subreddit_fundraising_goals_created_at'), table_name='subreddit_fundraising_goals')
    op.drop_index(op.f('ix_subreddit_fundraising_goals_completed_at'), table_name='subreddit_fundraising_goals')
    op.drop_table('subreddit_fundraising_goals')
    op.drop_index(op.f('ix_reddit_posts_subreddit_id'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_score'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_post_id'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_pipeline_run_id'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_num_comments'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_author'), table_name='reddit_posts')
    op.drop_table('reddit_posts')
    op.drop_index(op.f('ix_pipeline_run_usages_pipeline_run_id'), table_name='pipeline_run_usages')
    op.drop_index(op.f('ix_pipeline_run_usages_created_at'), table_name='pipeline_run_usages')
    op.drop_table('pipeline_run_usages')
    op.drop_index(op.f('ix_error_logs_timestamp'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_severity'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_pipeline_run_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_error_type'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_component'), table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_subreddits_updated_at'), table_name='subreddits')
    op.drop_index(op.f('ix_subreddits_subscribers'), table_name='subreddits')
    op.drop_index(op.f('ix_subreddits_subreddit_name'), table_name='subreddits')
    op.drop_index(op.f('ix_subreddits_reddit_id'), table_name='subreddits')
    op.drop_index(op.f('ix_subreddits_reddit_fullname'), table_name='subreddits')
    op.drop_index(op.f('ix_subreddits_created_utc'), table_name='subreddits')
    op.drop_index(op.f('ix_subreddits_created_at'), table_name='subreddits')
    op.drop_table('subreddits')
    op.drop_index(op.f('ix_sponsor_tiers_name'), table_name='sponsor_tiers')
    op.drop_index(op.f('ix_sponsor_tiers_min_amount'), table_name='sponsor_tiers')
    op.drop_index(op.f('ix_sponsor_tiers_created_at'), table_name='sponsor_tiers')
    op.drop_table('sponsor_tiers')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_start_time'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_end_time'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
