"""Add pipeline tasks table for task queue system

Revision ID: 5b4dfd9acad8
Revises: d9457e17822d
Create Date: 2025-06-26 12:05:23.628395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4dfd9acad8'
down_revision: Union[str, None] = 'd9457e17822d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_tasks_completed_at'), 'pipeline_tasks', ['completed_at'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_created_at'), 'pipeline_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_priority'), 'pipeline_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_scheduled_for'), 'pipeline_tasks', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_sponsor_id'), 'pipeline_tasks', ['sponsor_id'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_status'), 'pipeline_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_subreddit'), 'pipeline_tasks', ['subreddit'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_type'), 'pipeline_tasks', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_tasks_type'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_subreddit'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_status'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_sponsor_id'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_scheduled_for'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_priority'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_created_at'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_completed_at'), table_name='pipeline_tasks')
    op.drop_table('pipeline_tasks')
    # ### end Alembic commands ###
