"""add_donations_table

Revision ID: 6a14f81bd278
Revises: 99529e2f315b
Create Date: 2025-06-26 06:41:04.202520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a14f81bd278'
down_revision: Union[str, None] = '99529e2f315b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('stripe_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_created_at'), 'donations', ['created_at'], unique=False)
    op.create_index(op.f('ix_donations_customer_email'), 'donations', ['customer_email'], unique=False)
    op.create_index(op.f('ix_donations_status'), 'donations', ['status'], unique=False)
    op.create_index(op.f('ix_donations_stripe_payment_intent_id'), 'donations', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_donations_updated_at'), 'donations', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_updated_at'), table_name='donations')
    op.drop_index(op.f('ix_donations_stripe_payment_intent_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_status'), table_name='donations')
    op.drop_index(op.f('ix_donations_customer_email'), table_name='donations')
    op.drop_index(op.f('ix_donations_created_at'), table_name='donations')
    op.drop_table('donations')
    # ### end Alembic commands ###
