"""add comment_summary to RedditPost and remove CommentSummary table

Revision ID: 75ba0fc4509a
Revises: 0ba9ef219ecf
Create Date: 2025-06-18 13:32:54.569708

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75ba0fc4509a"
down_revision: Union[str, None] = "0ba9ef219ecf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interaction_agent_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_info_id", sa.Integer(), nullable=False),
        sa.Column("reddit_post_id", sa.Integer(), nullable=False),
        sa.Column("action_type", sa.String(length=32), nullable=True),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.String(length=32), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("subreddit", sa.String(length=64), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("success", sa.String(length=8), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("context_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_info_id"], ["product_infos.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reddit_post_id"], ["reddit_posts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interaction_agent_actions_action_type"),
        "interaction_agent_actions",
        ["action_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_agent_actions_product_info_id"),
        "interaction_agent_actions",
        ["product_info_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_agent_actions_reddit_post_id"),
        "interaction_agent_actions",
        ["reddit_post_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_agent_actions_subreddit"),
        "interaction_agent_actions",
        ["subreddit"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_agent_actions_success"),
        "interaction_agent_actions",
        ["success"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_agent_actions_target_id"),
        "interaction_agent_actions",
        ["target_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_agent_actions_target_type"),
        "interaction_agent_actions",
        ["target_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_agent_actions_timestamp"),
        "interaction_agent_actions",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_interaction_agent_actions_timestamp"),
        table_name="interaction_agent_actions",
    )
    op.drop_index(
        op.f("ix_interaction_agent_actions_target_type"),
        table_name="interaction_agent_actions",
    )
    op.drop_index(
        op.f("ix_interaction_agent_actions_target_id"),
        table_name="interaction_agent_actions",
    )
    op.drop_index(
        op.f("ix_interaction_agent_actions_success"),
        table_name="interaction_agent_actions",
    )
    op.drop_index(
        op.f("ix_interaction_agent_actions_subreddit"),
        table_name="interaction_agent_actions",
    )
    op.drop_index(
        op.f("ix_interaction_agent_actions_reddit_post_id"),
        table_name="interaction_agent_actions",
    )
    op.drop_index(
        op.f("ix_interaction_agent_actions_product_info_id"),
        table_name="interaction_agent_actions",
    )
    op.drop_index(
        op.f("ix_interaction_agent_actions_action_type"),
        table_name="interaction_agent_actions",
    )
    op.drop_table("interaction_agent_actions")
    # ### end Alembic commands ###
