"""add comment_summary to RedditPost and remove CommentSummary table

Revision ID: 858a6e07f47d
Revises: 75ba0fc4509a
Create Date: 2025-06-18 13:37:40.230376

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "858a6e07f47d"
down_revision: Union[str, None] = "75ba0fc4509a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
