"""Add stripe_refund_id to donations table

Revision ID: 885bd979b52a
Revises: 62b5a2d716c9
Create Date: 2025-07-14 09:23:51.310292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885bd979b52a'
down_revision: Union[str, Sequence[str], None] = '62b5a2d716c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('stripe_refund_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_donations_stripe_refund_id'), 'donations', ['stripe_refund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_stripe_refund_id'), table_name='donations')
    op.drop_column('donations', 'stripe_refund_id')
    # ### end Alembic commands ###
