"""add_subreddit_to_donations

Revision ID: b5de384eb7e0
Revises: 6a14f81bd278
Create Date: 2025-06-26 09:15:43.491035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5de384eb7e0'
down_revision: Union[str, None] = '6a14f81bd278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('subreddit', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_donations_subreddit'), 'donations', ['subreddit'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_subreddit'), table_name='donations')
    op.drop_column('donations', 'subreddit')
    # ### end Alembic commands ###
