"""add_scheduler_config_table

Revision ID: ceef82c66876
Revises: cac58179b196
Create Date: 2025-07-14 21:46:43.363989

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ceef82c66876"
down_revision: Union[str, Sequence[str], None] = "cac58179b196"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduler_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("interval_hours", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduler_config_created_at"),
        "scheduler_config",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduler_config_enabled"),
        "scheduler_config",
        ["enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduler_config_last_run_at"),
        "scheduler_config",
        ["last_run_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduler_config_next_run_at"),
        "scheduler_config",
        ["next_run_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduler_config_updated_at"),
        "scheduler_config",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduler_config_updated_at"), table_name="scheduler_config")
    op.drop_index(
        op.f("ix_scheduler_config_next_run_at"), table_name="scheduler_config"
    )
    op.drop_index(
        op.f("ix_scheduler_config_last_run_at"), table_name="scheduler_config"
    )
    op.drop_index(op.f("ix_scheduler_config_enabled"), table_name="scheduler_config")
    op.drop_index(op.f("ix_scheduler_config_created_at"), table_name="scheduler_config")
    op.drop_table("scheduler_config")
    # ### end Alembic commands ###
