"""initial schema with all tables including PipelineRunUsage

Revision ID: d10697a0f93c
Revises: 
Create Date: 2025-06-24 14:08:32.666016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10697a0f93c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_end_time'), 'pipeline_runs', ['end_time'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_start_time'), 'pipeline_runs', ['start_time'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('component', sa.String(length=64), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_component'), 'error_logs', ['component'], unique=False)
    op.create_index(op.f('ix_error_logs_error_type'), 'error_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_error_logs_pipeline_run_id'), 'error_logs', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_error_logs_severity'), 'error_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_error_logs_timestamp'), 'error_logs', ['timestamp'], unique=False)
    op.create_table('pipeline_run_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('idea_model', sa.String(length=64), nullable=False),
    sa.Column('image_model', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('image_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_run_usages_created_at'), 'pipeline_run_usages', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_run_usages_pipeline_run_id'), 'pipeline_run_usages', ['pipeline_run_id'], unique=True)
    op.create_table('reddit_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('subreddit', sa.String(length=64), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('comment_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_posts_pipeline_run_id'), 'reddit_posts', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_reddit_posts_post_id'), 'reddit_posts', ['post_id'], unique=True)
    op.create_index(op.f('ix_reddit_posts_subreddit'), 'reddit_posts', ['subreddit'], unique=False)
    op.create_table('product_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('reddit_post_id', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=256), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('affiliate_link', sa.Text(), nullable=True),
    sa.Column('template_id', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('product_type', sa.String(length=64), nullable=True),
    sa.Column('design_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reddit_post_id'], ['reddit_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_infos_model'), 'product_infos', ['model'], unique=False)
    op.create_index(op.f('ix_product_infos_pipeline_run_id'), 'product_infos', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_product_infos_product_type'), 'product_infos', ['product_type'], unique=False)
    op.create_index(op.f('ix_product_infos_reddit_post_id'), 'product_infos', ['reddit_post_id'], unique=False)
    op.create_index(op.f('ix_product_infos_template_id'), 'product_infos', ['template_id'], unique=False)
    op.create_index(op.f('ix_product_infos_theme'), 'product_infos', ['theme'], unique=False)
    op.create_table('interaction_agent_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_info_id', sa.Integer(), nullable=False),
    sa.Column('reddit_post_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('subreddit', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('success', sa.String(length=8), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['product_info_id'], ['product_infos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reddit_post_id'], ['reddit_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_agent_actions_action_type'), 'interaction_agent_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_interaction_agent_actions_product_info_id'), 'interaction_agent_actions', ['product_info_id'], unique=False)
    op.create_index(op.f('ix_interaction_agent_actions_reddit_post_id'), 'interaction_agent_actions', ['reddit_post_id'], unique=False)
    op.create_index(op.f('ix_interaction_agent_actions_subreddit'), 'interaction_agent_actions', ['subreddit'], unique=False)
    op.create_index(op.f('ix_interaction_agent_actions_success'), 'interaction_agent_actions', ['success'], unique=False)
    op.create_index(op.f('ix_interaction_agent_actions_target_id'), 'interaction_agent_actions', ['target_id'], unique=False)
    op.create_index(op.f('ix_interaction_agent_actions_target_type'), 'interaction_agent_actions', ['target_type'], unique=False)
    op.create_index(op.f('ix_interaction_agent_actions_timestamp'), 'interaction_agent_actions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_agent_actions_timestamp'), table_name='interaction_agent_actions')
    op.drop_index(op.f('ix_interaction_agent_actions_target_type'), table_name='interaction_agent_actions')
    op.drop_index(op.f('ix_interaction_agent_actions_target_id'), table_name='interaction_agent_actions')
    op.drop_index(op.f('ix_interaction_agent_actions_success'), table_name='interaction_agent_actions')
    op.drop_index(op.f('ix_interaction_agent_actions_subreddit'), table_name='interaction_agent_actions')
    op.drop_index(op.f('ix_interaction_agent_actions_reddit_post_id'), table_name='interaction_agent_actions')
    op.drop_index(op.f('ix_interaction_agent_actions_product_info_id'), table_name='interaction_agent_actions')
    op.drop_index(op.f('ix_interaction_agent_actions_action_type'), table_name='interaction_agent_actions')
    op.drop_table('interaction_agent_actions')
    op.drop_index(op.f('ix_product_infos_theme'), table_name='product_infos')
    op.drop_index(op.f('ix_product_infos_template_id'), table_name='product_infos')
    op.drop_index(op.f('ix_product_infos_reddit_post_id'), table_name='product_infos')
    op.drop_index(op.f('ix_product_infos_product_type'), table_name='product_infos')
    op.drop_index(op.f('ix_product_infos_pipeline_run_id'), table_name='product_infos')
    op.drop_index(op.f('ix_product_infos_model'), table_name='product_infos')
    op.drop_table('product_infos')
    op.drop_index(op.f('ix_reddit_posts_subreddit'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_post_id'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_pipeline_run_id'), table_name='reddit_posts')
    op.drop_table('reddit_posts')
    op.drop_index(op.f('ix_pipeline_run_usages_pipeline_run_id'), table_name='pipeline_run_usages')
    op.drop_index(op.f('ix_pipeline_run_usages_created_at'), table_name='pipeline_run_usages')
    op.drop_table('pipeline_run_usages')
    op.drop_index(op.f('ix_error_logs_timestamp'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_severity'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_pipeline_run_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_error_type'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_component'), table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_start_time'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_end_time'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
