"""Add tier system and simplify donation schema

Revision ID: d12899ded404
Revises: 2c1bf2279e63
Create Date: 2025-06-30 20:07:13.419903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12899ded404'
down_revision: Union[str, None] = '2c1bf2279e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsor_tiers_created_at'), table_name='sponsor_tiers')
    op.drop_index(op.f('ix_sponsor_tiers_min_amount'), table_name='sponsor_tiers')
    op.drop_index(op.f('ix_sponsor_tiers_name'), table_name='sponsor_tiers')
    op.drop_table('sponsor_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_completed_at'), table_name='subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_created_at'), table_name='subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_min_total_donation'), table_name='subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_status'), table_name='subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_subreddit_id'), table_name='subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_tier_level'), table_name='subreddit_tiers')
    op.drop_table('subreddit_tiers')
    op.drop_index(op.f('ix_sponsors_created_at'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_donation_id'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_status'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_subreddit_id'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_tier_id'), table_name='sponsors')
    op.drop_table('sponsors')
    op.add_column('donations', sa.Column('tier', sa.String(length=32), nullable=False, server_default='bronze'))
    op.add_column('donations', sa.Column('commission_type', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_donations_commission_type'), 'donations', ['commission_type'], unique=False)
    op.create_index(op.f('ix_donations_tier'), 'donations', ['tier'], unique=False)
    op.add_column('pipeline_tasks', sa.Column('donation_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_pipeline_tasks_sponsor_id'), table_name='pipeline_tasks')
    op.create_index(op.f('ix_pipeline_tasks_donation_id'), 'pipeline_tasks', ['donation_id'], unique=False)
    op.drop_constraint(None, 'pipeline_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_tasks', 'donations', ['donation_id'], ['id'])
    op.drop_column('pipeline_tasks', 'sponsor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_tasks', sa.Column('sponsor_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'pipeline_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_tasks', 'sponsors', ['sponsor_id'], ['id'])
    op.drop_index(op.f('ix_pipeline_tasks_donation_id'), table_name='pipeline_tasks')
    op.create_index(op.f('ix_pipeline_tasks_sponsor_id'), 'pipeline_tasks', ['sponsor_id'], unique=False)
    op.drop_column('pipeline_tasks', 'donation_id')
    op.drop_index(op.f('ix_donations_tier'), table_name='donations')
    op.drop_index(op.f('ix_donations_commission_type'), table_name='donations')
    op.drop_column('donations', 'commission_type')
    op.drop_column('donations', 'tier')
    op.create_table('sponsors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('donation_id', sa.INTEGER(), nullable=False),
    sa.Column('tier_id', sa.INTEGER(), nullable=False),
    sa.Column('subreddit_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['sponsor_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsors_tier_id'), 'sponsors', ['tier_id'], unique=False)
    op.create_index(op.f('ix_sponsors_subreddit_id'), 'sponsors', ['subreddit_id'], unique=False)
    op.create_index(op.f('ix_sponsors_status'), 'sponsors', ['status'], unique=False)
    op.create_index(op.f('ix_sponsors_donation_id'), 'sponsors', ['donation_id'], unique=False)
    op.create_index(op.f('ix_sponsors_created_at'), 'sponsors', ['created_at'], unique=False)
    op.create_table('subreddit_tiers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subreddit_id', sa.INTEGER(), nullable=False),
    sa.Column('tier_level', sa.INTEGER(), nullable=False),
    sa.Column('min_total_donation', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subreddit_tiers_tier_level'), 'subreddit_tiers', ['tier_level'], unique=False)
    op.create_index(op.f('ix_subreddit_tiers_subreddit_id'), 'subreddit_tiers', ['subreddit_id'], unique=False)
    op.create_index(op.f('ix_subreddit_tiers_status'), 'subreddit_tiers', ['status'], unique=False)
    op.create_index(op.f('ix_subreddit_tiers_min_total_donation'), 'subreddit_tiers', ['min_total_donation'], unique=False)
    op.create_index(op.f('ix_subreddit_tiers_created_at'), 'subreddit_tiers', ['created_at'], unique=False)
    op.create_index(op.f('ix_subreddit_tiers_completed_at'), 'subreddit_tiers', ['completed_at'], unique=False)
    op.create_table('sponsor_tiers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('min_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('benefits', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsor_tiers_name'), 'sponsor_tiers', ['name'], unique=1)
    op.create_index(op.f('ix_sponsor_tiers_min_amount'), 'sponsor_tiers', ['min_amount'], unique=False)
    op.create_index(op.f('ix_sponsor_tiers_created_at'), 'sponsor_tiers', ['created_at'], unique=False)
    # ### end Alembic commands ###
