"""Add agent_ratings JSON field to AgentScannedPost

Revision ID: d848fa9e3ee9
Revises: 0c44bf314eb7
Create Date: 2025-07-17 12:35:42.536503

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d848fa9e3ee9"
down_revision: Union[str, Sequence[str], None] = "0c44bf314eb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_scanned_posts", sa.Column("agent_ratings", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_scanned_posts", "agent_ratings")
    # ### end Alembic commands ###
