"""Add sponsor tiers, sponsors, subreddit tiers, and fundraising goals tables

Revision ID: d9457e17822d
Revises: 296335745ad1
Create Date: 2025-06-26 11:58:23.628395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9457e17822d'
down_revision: Union[str, None] = '296335745ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsor_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsor_tiers_created_at'), 'sponsor_tiers', ['created_at'], unique=False)
    op.create_index(op.f('ix_sponsor_tiers_min_amount'), 'sponsor_tiers', ['min_amount'], unique=False)
    op.create_index(op.f('ix_sponsor_tiers_name'), 'sponsor_tiers', ['name'], unique=True)
    op.create_table('subreddit_fundraising_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=False),
    sa.Column('goal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subreddit_fundraising_goals_completed_at'), 'subreddit_fundraising_goals', ['completed_at'], unique=False)
    op.create_index(op.f('ix_subreddit_fundraising_goals_created_at'), 'subreddit_fundraising_goals', ['created_at'], unique=False)
    op.create_index(op.f('ix_subreddit_fundraising_goals_current_amount'), 'subreddit_fundraising_goals', ['current_amount'], unique=False)
    op.create_index(op.f('ix_subreddit_fundraising_goals_deadline'), 'subreddit_fundraising_goals', ['deadline'], unique=False)
    op.create_index(op.f('ix_subreddit_fundraising_goals_goal_amount'), 'subreddit_fundraising_goals', ['goal_amount'], unique=False)
    op.create_index(op.f('ix_subreddit_fundraising_goals_status'), 'subreddit_fundraising_goals', ['status'], unique=False)
    op.create_index(op.f('ix_subreddit_fundraising_goals_subreddit'), 'subreddit_fundraising_goals', ['subreddit'], unique=False)
    op.create_table('subreddit_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=False),
    sa.Column('tier_level', sa.Integer(), nullable=False),
    sa.Column('min_total_donation', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subreddit_tiers_completed_at'), 'subreddit_tiers', ['completed_at'], unique=False)
    op.create_index(op.f('ix_subreddit_tiers_created_at'), 'subreddit_tiers', ['created_at'], unique=False)
    op.create_index(op.f('ix_subreddit_tiers_min_total_donation'), 'subreddit_tiers', ['min_total_donation'], unique=False)
    op.create_index(op.f('ix_subreddit_tiers_status'), 'subreddit_tiers', ['status'], unique=False)
    op.create_index(op.f('ix_subreddit_tiers_subreddit'), 'subreddit_tiers', ['subreddit'], unique=False)
    op.create_index(op.f('ix_subreddit_tiers_tier_level'), 'subreddit_tiers', ['tier_level'], unique=False)
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_id'], ['sponsor_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsors_created_at'), 'sponsors', ['created_at'], unique=False)
    op.create_index(op.f('ix_sponsors_donation_id'), 'sponsors', ['donation_id'], unique=False)
    op.create_index(op.f('ix_sponsors_status'), 'sponsors', ['status'], unique=False)
    op.create_index(op.f('ix_sponsors_subreddit'), 'sponsors', ['subreddit'], unique=False)
    op.create_index(op.f('ix_sponsors_tier_id'), 'sponsors', ['tier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsors_tier_id'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_subreddit'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_status'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_donation_id'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_created_at'), table_name='sponsors')
    op.drop_table('sponsors')
    op.drop_index(op.f('ix_subreddit_tiers_tier_level'), table_name='subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_subreddit'), table_name='subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_status'), table_name='subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_min_total_donation'), table_name='subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_created_at'), table_name='subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_tiers_completed_at'), table_name='subreddit_tiers')
    op.drop_table('subreddit_tiers')
    op.drop_index(op.f('ix_subreddit_fundraising_goals_subreddit'), table_name='subreddit_fundraising_goals')
    op.drop_index(op.f('ix_subreddit_fundraising_goals_status'), table_name='subreddit_fundraising_goals')
    op.drop_index(op.f('ix_subreddit_fundraising_goals_goal_amount'), table_name='subreddit_fundraising_goals')
    op.drop_index(op.f('ix_subreddit_fundraising_goals_deadline'), table_name='subreddit_fundraising_goals')
    op.drop_index(op.f('ix_subreddit_fundraising_goals_current_amount'), table_name='subreddit_fundraising_goals')
    op.drop_index(op.f('ix_subreddit_fundraising_goals_created_at'), table_name='subreddit_fundraising_goals')
    op.drop_index(op.f('ix_subreddit_fundraising_goals_completed_at'), table_name='subreddit_fundraising_goals')
    op.drop_table('subreddit_fundraising_goals')
    op.drop_index(op.f('ix_sponsor_tiers_name'), table_name='sponsor_tiers')
    op.drop_index(op.f('ix_sponsor_tiers_min_amount'), table_name='sponsor_tiers')
    op.drop_index(op.f('ix_sponsor_tiers_created_at'), table_name='sponsor_tiers')
    op.drop_table('sponsor_tiers')
    # ### end Alembic commands ###
