"""add_commission_fields_to_donations

Revision ID: e094d5e5c9ed
Revises: 32a1a538ffb1
Create Date: 2025-06-26 16:55:56.627673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e094d5e5c9ed'
down_revision: Union[str, None] = '32a1a538ffb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('donation_type', sa.String(length=32), nullable=False))
    op.add_column('donations', sa.Column('post_id', sa.String(length=32), nullable=True))
    op.add_column('donations', sa.Column('commission_message', sa.Text(), nullable=True))
    op.create_index(op.f('ix_donations_donation_type'), 'donations', ['donation_type'], unique=False)
    op.create_index(op.f('ix_donations_post_id'), 'donations', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_post_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_donation_type'), table_name='donations')
    op.drop_column('donations', 'commission_message')
    op.drop_column('donations', 'post_id')
    op.drop_column('donations', 'donation_type')
    # ### end Alembic commands ###
