"""
Data models for the Zazzle Agent application.

This module defines the core data structures used throughout the application,
including product information, Reddit context, distribution metadata, and more.
Each class is designed to be serializable and includes utility methods for
conversion between different formats (dict, JSON, CSV).
"""

from dataclasses import dataclass, asdict, is_dataclass
from typing import Optional, Dict, Any, List
from datetime import datetime, timezone
from enum import Enum
import csv
import os
import json
from app.utils.logging_config import get_logger

logger = get_logger(__name__)

class ContentType(Enum):
    """
    Types of content that can be generated for a product.
    
    Currently supports:
        REDDIT: Content sourced from Reddit posts
    """
    REDDIT = "REDDIT"


class DistributionStatus(Enum):
    """
    Status of content distribution across channels.
    
    States:
        PENDING: Content is queued for distribution
        PUBLISHED: Content has been successfully published
        FAILED: Distribution attempt failed
    """
    PENDING = "PENDING"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"


@dataclass
class DistributionMetadata:
    """
    Metadata for content distribution to a specific channel.
    
    This class tracks the status and details of content distribution
    across different channels (e.g., social media platforms).
    
    Attributes:
        channel: The distribution channel name
        status: Current distribution status
        published_at: Timestamp when content was published
        channel_id: Platform-specific identifier (e.g., tweet ID)
        channel_url: URL to the published content
        error_message: Error details if distribution failed
    """
    channel: str
    status: DistributionStatus
    published_at: Optional[datetime] = None
    channel_id: Optional[str] = None  # e.g., tweet ID
    channel_url: Optional[str] = None  # e.g., tweet URL
    error_message: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert metadata to dictionary format.
        
        Returns:
            Dictionary representation of the metadata with datetime
            objects converted to ISO format strings.
        """
        data = {
            'channel': self.channel,
            'status': self.status.value,
            'published_at': self.published_at.isoformat() if self.published_at else None,
            'channel_id': self.channel_id,
            'channel_url': self.channel_url,
            'error_message': self.error_message
        }
        return data

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'DistributionMetadata':
        """
        Create metadata instance from dictionary.
        
        Args:
            data: Dictionary containing metadata fields
            
        Returns:
            DistributionMetadata instance
            
        Note:
            Handles conversion of ISO format datetime strings back to datetime objects
        """
        published_at = None
        if data.get('published_at'):
            try:
                published_at = datetime.fromisoformat(data['published_at'])
            except ValueError:
                pass

        return cls(
            channel=data['channel'],
            status=DistributionStatus(data['status']),
            published_at=published_at,
            channel_id=data.get('channel_id'),
            channel_url=data.get('channel_url'),
            error_message=data.get('error_message')
        )


@dataclass
class PipelineConfig:
    """
    Configuration information used in main pipeline logic.
    
    This class holds configuration settings that control the behavior
    of the product creation pipeline.
    
    Attributes:
        model: The AI model to use (e.g. "dall-e-3")
        zazzle_template_id: The Zazzle template ID for product creation
        zazzle_tracking_code: The tracking code for Zazzle affiliate links
        prompt_version: Version of the prompt being used
    """
    model: str
    zazzle_template_id: str
    zazzle_tracking_code: str
    prompt_version: str = "1.0.0"

    def log(self):
        """Log the configuration details to the application logger."""
        logger.info("Pipeline Configuration:")
        logger.info(f"Model: {self.model}")
        logger.info(f"Template ID: {self.zazzle_template_id}")
        logger.info(f"Tracking Code: {self.zazzle_tracking_code}")
        logger.info(f"Prompt Version: {self.prompt_version}")


@dataclass
class RedditContext:
    """
    Data generated by and relevant to the reddit agent.
    
    This class encapsulates all information related to a Reddit post
    that is being used as source material for product creation.
    
    Attributes:
        post_id: The Reddit post ID
        post_title: The title of the Reddit post
        post_url: The full URL to the Reddit post
        subreddit: The subreddit name
        post_content: Optional content/body of the post
        comments: Optional list of comments on the post
    """
    post_id: str
    post_title: str
    post_url: str
    subreddit: str
    post_content: Optional[str] = None
    comments: Optional[List[Dict[str, Any]]] = None

    def log(self):
        """Log the Reddit context details to the application logger."""
        logger.info("Reddit Context:")
        logger.info(f"Post ID: {self.post_id}")
        logger.info(f"Title: {self.post_title}")
        logger.info(f"URL: {self.post_url}")
        logger.info(f"Subreddit: {self.subreddit}")
        if self.post_content:
            logger.info(f"Content: {self.post_content[:100]}...")  # Log first 100 chars
        if self.comments:
            logger.info(f"Number of comments: {len(self.comments)}")


@dataclass
class ProductIdea:
    """
    Data about the product design process.
    
    This class represents the initial concept and design instructions
    for creating a product, including the source Reddit content.
    
    Attributes:
        theme: The main theme/idea for the product
        image_description: Description for image generation
        design_instructions: Instructions for product design
        reddit_context: The Reddit context this idea came from
        model: The AI model used
        prompt_version: Version of the prompt used
    """
    theme: str
    image_description: str
    design_instructions: Dict[str, Any]
    reddit_context: RedditContext
    model: str
    prompt_version: str

    def log(self):
        """Log the product idea details to the application logger."""
        logger.info("Product Idea:")
        logger.info(f"Theme: {self.theme}")
        logger.info(f"Image Description: {self.image_description}")
        logger.info(f"Model: {self.model}")
        logger.info(f"Prompt Version: {self.prompt_version}")
        logger.info("Design Instructions:")
        for key, value in self.design_instructions.items():
            logger.info(f"  {key}: {value}")
        self.reddit_context.log()


@dataclass
class ProductInfo:
    """
    The product data created by the ZazzleProductDesigner.
    
    This class represents a complete product with all its associated
    metadata, including design details, source information, and URLs.
    
    Attributes:
        product_id: Unique identifier for the product
        name: Product name
        product_type: Type of product (e.g. "sticker")
        image_url: URL to the product image
        product_url: URL to the Zazzle product page
        zazzle_template_id: The Zazzle template ID used
        zazzle_tracking_code: The tracking code used
        theme: The product theme
        model: The AI model used
        prompt_version: Version of the prompt used
        reddit_context: The Reddit context this product came from
        design_instructions: The design instructions used
        image_local_path: Optional path to local image file
        affiliate_link: Optional Zazzle affiliate link
    """
    product_id: str
    name: str
    product_type: str
    image_url: str
    product_url: str
    zazzle_template_id: str
    zazzle_tracking_code: str
    theme: str
    model: str
    prompt_version: str
    reddit_context: RedditContext
    design_instructions: Dict[str, Any]
    image_local_path: Optional[str] = None
    affiliate_link: Optional[str] = None

    def log(self):
        """Log the product information to the application logger."""
        logger.info("Product Information:")
        logger.info(f"ID: {self.product_id}")
        logger.info(f"Name: {self.name}")
        logger.info(f"Type: {self.product_type}")
        logger.info(f"Image URL: {self.image_url}")
        logger.info(f"Product URL: {self.product_url}")
        logger.info(f"Template ID: {self.zazzle_template_id}")
        logger.info(f"Theme: {self.theme}")
        logger.info(f"Model: {self.model}")
        logger.info(f"Prompt Version: {self.prompt_version}")
        if self.image_local_path:
            logger.info(f"Local Image Path: {self.image_local_path}")
        if self.affiliate_link:
            logger.info(f"Affiliate Link: {self.affiliate_link}")
        self.reddit_context.log()

    def to_csv(self, filename: str) -> None:
        """
        Save product data to CSV file.
        
        Args:
            filename: Path to the CSV file
            
        Note:
            If the file doesn't exist, it will be created with headers.
            If it exists, data will be appended to the existing file.
        """
        # Convert to dict and ensure all fields exist
        data = asdict(self)
        
        # Write to CSV
        file_exists = os.path.isfile(filename)
        with open(filename, 'a', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=data.keys())
            if not file_exists:
                writer.writeheader()
            writer.writerow(data)

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert product to dictionary format.
        
        Returns:
            Dictionary representation of the product with:
            - RedditContext converted to dict
            - datetime objects converted to ISO format strings
            - design_instructions serialized as JSON string
        """
        data = asdict(self)
        # Convert RedditContext to dict only if it's a dataclass instance
        if data.get('reddit_context') and is_dataclass(data['reddit_context']):
            data['reddit_context'] = asdict(data['reddit_context'])
        # Convert datetime objects to strings
        for key, value in data.items():
            if isinstance(value, datetime):
                data[key] = value.isoformat()
        # Serialize design_instructions as JSON string
        if 'design_instructions' in data and isinstance(data['design_instructions'], dict):
            data['design_instructions'] = json.dumps(data['design_instructions'])
        return data

    def to_json(self) -> str:
        """
        Convert product to JSON string.
        
        Returns:
            JSON string representation of the product
        """
        return json.dumps(self.to_dict())

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'ProductInfo':
        """
        Create product instance from dictionary.
        
        Args:
            data: Dictionary containing product fields
            
        Returns:
            ProductInfo instance
            
        Note:
            Handles conversion of RedditContext from dict back to object
        """
        if isinstance(data, ProductInfo):
            return data
        
        # Convert reddit_context dict back to RedditContext object
        reddit_context = data.get('reddit_context')
        if isinstance(reddit_context, dict):
            data['reddit_context'] = RedditContext(**reddit_context)
        
        return cls(**data)

    @staticmethod
    def generate_identifier(product_id: str) -> str:
        """
        Generate a unique identifier for a product.
        
        Args:
            product_id: Base product ID
            
        Returns:
            Unique identifier combining product ID and timestamp
        """
        return f"{product_id}_{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"


@dataclass
class DesignInstructions:
    """
    Instructions for creating a product design.
    
    This class contains all the parameters needed to create a product
    design, including image, theme, text, and other customization options.
    
    Attributes:
        image: URL of the image to use
        theme: Optional theme for the product
        text: Optional text to include
        color: Optional color specification
        quantity: Optional quantity
        product_type: Type of product (e.g. "sticker")
        template_id: Optional template ID to use
        model: Optional AI model used
        prompt_version: Optional version of the prompt used
    """
    image: str
    theme: Optional[str] = None
    text: Optional[str] = None
    color: Optional[str] = None
    quantity: Optional[int] = None
    product_type: str = "sticker"
    template_id: Optional[str] = None
    model: Optional[str] = None
    prompt_version: Optional[str] = None 